import Head from 'next/head'
import type { AppProps } from "next/app"
import type { NextPage } from "next"

import "../styles/globals.css"
import "@fontsource/roboto/300.css"
import "@fontsource/roboto/400.css"
import "@fontsource/roboto/500.css"
import "@fontsource/roboto/700.css"

const App: NextPage<AppProps> = ({ Component, pageProps }) => {
    return (
        <>
            <Head>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
                <meta name="viewport" content="initial-scale=1, width=device-width" />
                <title>HotSeat</title>
            </Head>
            <Component {...pageProps} />
        </>
    )
}

export default App
