import type { AppProps } from "next/app"
import type { NextPage } from "next"
import Head from "next/head"
import { CacheProvider, EmotionCache } from "@emotion/react"
import { ThemeProvider, CssBaseline, createTheme } from "@mui/material"

import "@fontsource/roboto/300.css"
import "@fontsource/roboto/400.css"
import "@fontsource/roboto/500.css"
import "@fontsource/roboto/700.css"

import createEmotionCache from "../util/createEmotionCache"
import darkThemeOptions from "../styles/theme/dark"
import "../styles/globals.css"
interface MyAppProps extends AppProps {
    emotionCache?: EmotionCache
}

const clientSideEmotionCache = createEmotionCache()

const darkTheme = createTheme(darkThemeOptions)

const App: NextPage<MyAppProps> = ({ Component, pageProps }) => {
    const emotionCache = clientSideEmotionCache

    return (
        <>
            <Head>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
                <meta
                    name="viewport"
                    content="initial-scale=1, width=device-width"
                />
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
                <meta
                    name="viewport"
                    content="initial-scale=1, width=device-width"
                />
                <title>HotSeat</title>
                <title>HotSeat</title>
            </Head>
            <CacheProvider value={emotionCache}>
                <ThemeProvider theme={darkTheme}>
                    <CssBaseline />
                    <Component {...pageProps} />
                </ThemeProvider>
            </CacheProvider>
        </>
    )
}

export default App
